export const INCREMENT_NUMBER = 'INCREMENT_NUMBER';
export const DECREMENT_NUMBER = 'DECREMENT_NUMBER';
export const ADD_NUMBER = 'ADD_NUMBER';
export const SUB_NUMBER = 'SUB_NUMBER';
export const CHANGE_BANNERS = 'CHANGE_BANNERS';
export const CHANGE_RECOMMENDS = 'CHANGE_RECOMMENDS';
export const FETCH_HOME_MULTIDATA = 'FETCH_HOME_MULTIDATA';